accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile_view, name='profile'),
    path('users/', views.user_list, name='user_list'),
    path('users/delete/<int:user_id>/', views.delete_user, name='delete_user'),
    path('profile/delete/', views.delete_profile, name='delete_profile'),
    path('notifications/', views.notifications, name='notifications'),
    path('delete_notification/<int:notification_id>/', views.delete_notification, name='delete_notification'),

]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter
from blogs.api_views import BlogViewSet, CommentViewSet, NotificationViewSet
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Blog App API",
        default_version='v1',
        description="API для Blog-App",
        terms_of_service="https://www.example.com/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

router = DefaultRouter()
router.register(r'blogs', BlogViewSet)
router.register(r'comments', CommentViewSet)
router.register(r'notifications', NotificationViewSet, basename='notifications')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('blogs.urls')),
    path('api/', include(router.urls)),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

if settings.DEBUG:
    urlpatterns += [
        path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
        path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    ]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.blog_list, name='blog_list'),
    path('my-blogs/', views.my_blogs, name='my_blogs'),
    path('create/', views.create_blog, name='create_blog'),
    path('<int:pk>/', views.blog_detail, name='blog_detail'),
    path('<int:pk>/update/', views.update_blog, name='update_blog'),
    path('<int:pk>/delete/', views.delete_blog, name='delete_blog'),
    path('<int:pk>/like/', views.like_blog, name='like_blog'),
    path('<int:pk>/comment/', views.add_comment, name='add_comment'),
    path('<int:pk>/reply/<int:comment_id>/', views.add_reply, name='add_reply'),
    path('comment/<int:pk>/delete/', views.delete_comment, name='delete_comment'),
    path('comment/<int:pk>/update/', views.update_comment, name='update_comment'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username}'s profile"

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    try:
        instance.profile.save()
    except Profile.DoesNotExist:
        Profile.objects.create(user=instance)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class ProfileForm(forms.ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = Profile
        fields = ['bio', 'avatar']
        widgets = {
            'bio': forms.Textarea(attrs={'rows': 4}),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance:
            self.fields['email'].initial = self.instance.user.email

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from .forms import UserRegisterForm, ProfileForm
from blogs.models import Notification
from .models import Profile
from django.contrib.auth.models import User
from django.db.models import Q


def user_login(request):
    if request.method == 'POST':
        identifier = request.POST['username']
        password = request.POST['password']

        print("=== DEBUG ===")
        print("Entered:", identifier)
        print("Password:", password)

        try:
            user_obj = User.objects.get(
                Q(username=identifier) | Q(email=identifier))
            user = authenticate(
                request, username=user_obj.username, password=password)
        except User.DoesNotExist:
            user = None

        if user is not None:
            login(request, user)
            return redirect('blogs:blog_list')
        else:
            print("Authentication failed")

        return render(request, 'blogs/blog_list.html', {'error': 'Incorrect'})

    return render(request, 'accounts/login.html')


def user_logout(request):
    logout(request)
    return redirect('accounts:login')


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.email = form.cleaned_data['email']
            user.save()
            Profile.objects.create(user=user)
            login(request, user)
            return redirect('accounts:profile')
    else:
        form = UserRegisterForm()
    return render(request, 'accounts/register.html', {'form': form})


@login_required
def profile_view(request):
    try:
        profile = request.user.profile
    except Profile.DoesNotExist:
        profile = Profile.objects.create(user=request.user)
    
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')
    else:
        form = ProfileForm(instance=profile)
    
    return render(request, 'accounts/profile.html', {'form': form})


@login_required
def user_list(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden("For administrators only")
    users = User.objects.all()
    return render(request, 'accounts/user_list.html', {'users': users})


@login_required
def delete_user(request, user_id):
    if not request.user.is_superuser:
        return HttpResponseForbidden("For administrators only")
    user = User.objects.get(id=user_id)
    if user != request.user:
        user.delete()
    return redirect('accounts:user_list')


@login_required
def delete_profile(request):
    if request.method == 'POST':
        request.user.delete()
        return redirect('accounts:login')
    return render(request, 'accounts/delete_profile.html')


@login_required
def notifications(request):
    notifications = Notification.objects.filter(
        recipient=request.user).order_by('-created_at')
    notifications.filter(is_read=False).update(is_read=True)
    return render(request, 'accounts/notifications.html', {'notifications': notifications})


@login_required
def delete_notification(request, notification_id):
    try:
        notification = Notification.objects.get(
            id=notification_id, recipient=request.user)
        notification.delete()
        return redirect('accounts:notifications')
    except Notification.DoesNotExist:
        return HttpResponseForbidden("The notification was not found or does not belong to you.")

accounts/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Blog App{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="{% url 'blogs:blog_list' %}">Blog App</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                        {% if not user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:profile' %}">Profile</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:notifications' %}">Notifications</a>
                        </li>
                        {% if user.is_superuser %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:user_list' %}">Users</a>
                            </li>
                        {% endif %}

                       <li class="nav-item">
                            <a class="nav-link blogs" href="{% url 'blogs:create_blog' %}">Create Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link blogs" href="{% url 'blogs:my_blogs' %}">My Blogs</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:register' %}">Registration</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>